# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: starship/voicebot/proto/tts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='starship/voicebot/proto/tts.proto',
  package='skelterlabs.aiq.voicebot.v1alpha1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!starship/voicebot/proto/tts.proto\x12!skelterlabs.aiq.voicebot.v1alpha1\"\x1f\n\x1dSynthesizeSpeechRequestConfig\":\n!StreamingSynthesizeSpeechResponse\x12\x15\n\raudio_content\x18\x01 \x01(\x0c\x62\x06proto3'
)




_SYNTHESIZESPEECHREQUESTCONFIG = _descriptor.Descriptor(
  name='SynthesizeSpeechRequestConfig',
  full_name='skelterlabs.aiq.voicebot.v1alpha1.SynthesizeSpeechRequestConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=103,
)


_STREAMINGSYNTHESIZESPEECHRESPONSE = _descriptor.Descriptor(
  name='StreamingSynthesizeSpeechResponse',
  full_name='skelterlabs.aiq.voicebot.v1alpha1.StreamingSynthesizeSpeechResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_content', full_name='skelterlabs.aiq.voicebot.v1alpha1.StreamingSynthesizeSpeechResponse.audio_content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['SynthesizeSpeechRequestConfig'] = _SYNTHESIZESPEECHREQUESTCONFIG
DESCRIPTOR.message_types_by_name['StreamingSynthesizeSpeechResponse'] = _STREAMINGSYNTHESIZESPEECHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SynthesizeSpeechRequestConfig = _reflection.GeneratedProtocolMessageType('SynthesizeSpeechRequestConfig', (_message.Message,), {
  'DESCRIPTOR' : _SYNTHESIZESPEECHREQUESTCONFIG,
  '__module__' : 'starship.voicebot.proto.tts_pb2'
  # @@protoc_insertion_point(class_scope:skelterlabs.aiq.voicebot.v1alpha1.SynthesizeSpeechRequestConfig)
  })
_sym_db.RegisterMessage(SynthesizeSpeechRequestConfig)

StreamingSynthesizeSpeechResponse = _reflection.GeneratedProtocolMessageType('StreamingSynthesizeSpeechResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGSYNTHESIZESPEECHRESPONSE,
  '__module__' : 'starship.voicebot.proto.tts_pb2'
  # @@protoc_insertion_point(class_scope:skelterlabs.aiq.voicebot.v1alpha1.StreamingSynthesizeSpeechResponse)
  })
_sym_db.RegisterMessage(StreamingSynthesizeSpeechResponse)


# @@protoc_insertion_point(module_scope)
